# Text only

In [ ]:
# pip install transformers
from transformers import AutoModelForCausalLM, AutoTokenizer
checkpoint = "HuggingFaceTB/SmolLM-1.7B-Instruct"

device = "cuda" # for GPU usage or "cpu" for CPU usage
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(checkpoint).to(device)

tokenizer_config.json:   0%|          | 0.00/3.59k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/801k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/738 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.42G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

In [ ]:
messages = [{"role": "user", "content": "What is the capital of France."}]
input_text=tokenizer.apply_chat_template(messages, tokenize=False)
print(input_text)

<|im_start|>user
What is the capital of France.<|im_end|>



In [ ]:
inputs = tokenizer.encode(input_text, return_tensors="pt").to(device)
inputs

tensor([[   1, 4093,  198, 1780,  314,  260, 3575,  282, 4649,   30,    2,  198]],
       device='cuda:0')

In [ ]:
outputs = model.generate(inputs, max_new_tokens=50, temperature=0.2, top_p=0.9)
outputs

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


tensor([[    1,  4093,   198,  1780,   314,   260,  3575,   282,  4649,    30,
             2,   198,     1,   520,  9531,   198,   504,  3575,   282,  4649,
           314,  7042,    28,   527,   314,  3807,   281,   260,  4081,    29,
         19994,   599,   282,   260,  1798,    30,     2]], device='cuda:0')

In [ ]:
print(tokenizer.decode(outputs[0]))

<|im_start|>user
What is the capital of France.<|im_end|>
<|im_start|>assistant
The capital of France is Paris, which is located in the north-central part of the country.<|im_end|>


# Text + Image

In [ ]:
!pip install num2words

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
from transformers import AutoProcessor, AutoModelForImageTextToText
import torch

model_path = "HuggingFaceTB/SmolVLM2-2.2B-Instruct"
processor = AutoProcessor.from_pretrained(model_path)
model = AutoModelForImageTextToText.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16,
).to("cuda")

processor_config.json:   0%|          | 0.00/67.0 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/430 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/28.6k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/801k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.55M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/4.74k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/868 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/3.64k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/63.9k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/4.03G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

In [ ]:
!wget "https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png"

--2025-06-15 10:52:25--  https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png
Resolving upload.wikimedia.org (upload.wikimedia.org)... 198.35.26.112, 2620:0:863:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|198.35.26.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11063620 (11M) [image/png]
Saving to: ‘Image_created_with_a_mobile_phone.png’

Image_created_with_ 100%[===================>]  10.55M  24.7MB/s    in 0.4s    

2025-06-15 10:52:26 (24.7 MB/s) - ‘Image_created_with_a_mobile_phone.png’ saved [11063620/11063620]



In [ ]:
from PIL import Image
image_path = '/content/Image_created_with_a_mobile_phone.png'
image = Image.open(image_path)
image.resize((250, 250))

In [ ]:
image.resize((250, 250)).save(image_path)

In [ ]:
messages = [
    {
        "role": "user",
        "content": [
            {"type": "text", "text": "Describe the Image?"},
            {"type": "image", "path": image_path}
        ]
    }
]

messages

[{'role': 'user',
  'content': [{'type': 'text', 'text': 'Describe the Image?'},
   {'type': 'image',
    'path': '/content/Image_created_with_a_mobile_phone.png'}]}]

In [ ]:
inputs = processor.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device, dtype=torch.bfloat16)

inputs

{'pixel_values': tensor([[[[[-0.2559, -0.2559, -0.2559,  ..., -0.2793, -0.2793, -0.2871],
           [-0.2559, -0.2559, -0.2559,  ..., -0.2793, -0.2793, -0.2871],
           [-0.2559, -0.2559, -0.2559,  ..., -0.2793, -0.2793, -0.2871],
           ...,
           [-0.3652, -0.3652, -0.3730,  ..., -0.8906, -0.8828, -0.8828],
           [-0.3809, -0.3809, -0.3887,  ..., -0.8906, -0.8906, -0.8906],
           [-0.3965, -0.3965, -0.4043,  ..., -0.8984, -0.8906, -0.8906]],

          [[ 0.3418,  0.3418,  0.3418,  ...,  0.1924,  0.1846,  0.1846],
           [ 0.3418,  0.3418,  0.3418,  ...,  0.1924,  0.1846,  0.1846],
           [ 0.3340,  0.3340,  0.3340,  ...,  0.1924,  0.1846,  0.1846],
           ...,
           [ 0.1060,  0.0903,  0.0669,  ..., -0.8672, -0.8750, -0.8750],
           [ 0.0903,  0.0747,  0.0510,  ..., -0.8672, -0.8750, -0.8750],
           [ 0.0825,  0.0669,  0.0432,  ..., -0.8672, -0.8750, -0.8750]],

          [[ 0.9062,  0.9062,  0.9062,  ...,  0.7578,  0.7578,  0.7578]

In [ ]:
inputs.keys()

dict_keys(['pixel_values', 'pixel_attention_mask', 'input_ids', 'attention_mask'])

--> pixel_values

A tensor (e.g., torch.Tensor) containing the processed image data.

These are the normalized pixel values (after resizing, cropping, converting to tensors, etc.) for each image in your chat messages.

The processor uses its internal image handler to handle formats like URLs or local paths, preparing them for the model


--> pixel_attention_mask

Indicates which image patches are padding and which contain real image data.

For example, if images are resized or padded to a fixed shape, this mask ensures the model doesn’t “focus” on padded areas.

It parallels attention_mask in NLP, but for visual inputs
stackoverflow.com
.

--> input_ids

A tensor of token IDs representing your text.

These IDs come from the tokenizer interpreting your chat prompts (including system messages, user messages, assistant messages) according to the model’s chat template

--> attention_mask

A binary tensor (0s and 1s) marking which text tokens should be attended to and which are padding.

This ensures the model ignores padding tokens during processing (common in Transformers)

In [ ]:
generated_ids = model.generate(**inputs, max_new_tokens=64)
generated_ids

tensor([[    1, 11126,    42,  ...,   314,   260,  1085]], device='cuda:0')

In [ ]:
generated_texts = processor.batch_decode(
    generated_ids,
    skip_special_tokens=True,
)
print(generated_texts[0])

User: Describe the Image?





Assistant: The image captures a moment of solitude and tranquility, as a hand holds a smartphone, capturing the scene before it. The hand, clad in a black sleeve, is positioned on the right side of the frame, holding the phone up to the camera. The phone screen displays a photo of a bridge, which is the main


In [ ]:
# https://huggingface.co/HuggingFaceTB/SmolVLM-Instruct

# Audio based llm

In [ ]:
#https://huggingface.co/Qwen/Qwen-Audio-Chat

## Image underatnding of llm

In [ ]:
# Other applications of vllms
# OCR
# Image captioning
# object detection
# object segmentation

In [ ]:
# https://ai.google.dev/gemini-api/docs/image-understanding